### ISSUE TITLE
Convert CorpPass 'NULL' strings into nil

### ISSUE THREAD

**Issue by gyng** [idagds/libcorppass#36]
CorpPass 1.4 returns `NULL` for mandatory empty fields. We need to convert these into `nil`.

A change was introduced in CorpPass XML responses where mandatory tags will always contain values, including the string `NULL` for fields meant to be empty.

For example, a field `<CPNonUEN_RegNo>NULL</CPNonUEN_RegNo>` might hold the value `NULL`. Currently, a `CorpPass::User` object backed with this field will return a string `NULL` when the method `some_corppass_user.info.non_uen_reg_no` is called. We want the method to return `nil` instead.

### Acceptance criteria

**AC1**: `CorpPass::UserInfo` returns `nil` for fields backed by XML fields with `NULL` values

**AC2**: Classes in module `CorpPass::AuthAccess` return `nil` for fields backed by XML fields with `NULL` values

### General acceptance criteria

* Does not decrease code coverage (Rspec)
* Tests run on Travis CI and do not break the build

### Additional information

[The existing fixture](https://github.com/idagds/libcorppass/blob/master/spec/fixtures/corp_pass/attribute_value.xml) already has fields with `NULL`. The associated spec for this is in [user_spec.rb](https://github.com/idagds/libcorppass/blob/master/spec/corp_pass/user_spec.rb#L27).

**Comment by winston** [comment]
@lawliet89 @yangshun Just curious, why 👎 ? Might be helpful for IDA to understand your perspectives.

**Comment by lawliet89** [comment]
The 👎 was because of the need to even do this in the first place because of the specifications, rather than the task itself.

**Comment by gyng** [comment]
There have been major design changes to this library, so this task is no longer required and the auction is cancelled.
